### ISSUE TITLE
Is there any way to sort the messages ?

### ISSUE THREAD

**Issue by meditrine** [MessageKit/MessageKit#589] opened 2018-03-25 20:47 UTC
Hello,

Is there any way to sort the messages ?
I filled an array of messages with random dates and random ids to see how works this library,

But it seems like it is sorting by ids and not by dates, or maybe I missed something.

Thanks :)

**Comment by SD10** [comment] 2018-03-25 23:37
Hey @meditrine, this looks like a duplicate of #374. Can you move the discussion there?

**Closed as completed by SD10** 2018-03-25 23:37 UTC
Labels: question
