### ISSUE TITLE
Takes too much time while navigating from inbox to chat controller 

### ISSUE THREAD

**Issue by SarimAshfaq** [MessageKit/MessageKit#167] opened 2017-09-26 10:28 UTC
Tap on any message to proceed to chat controller and it takes a few seconds to open it.

**Comment by SD10** [comment] 2017-09-26 16:23
@SarimAshfaq Is this only an issue while running on the simulator? I've had this problem on my simulator for awhile. I can't reproduce on iPhone 7.

**Comment by Jeyhey** [comment] 2017-09-26 20:08
I could improve the time by doing the following:

- don't construct `Sender()` in `currentSender()`. Do it once in the controller, save it as instance variable and pass that variable to the function.

- same for `Avatar()` in `avatar(for message..)`

- don't construct `Sender()` for every `MessageType`. Use cached versions.

- don't construct date formatters in the callbacks. Use a cached instance.

- make sure to format the input bar only once (had it in `viewDidLoad()` and `viewWillAppear()`, I removed it from `viewWillAppear()` )

**Comment by SarimAshfaq** [comment] 2017-09-27 06:27
@Jeyhey thanks for your comment. By you comment I was able to figure out that problem was with the way I was downloading images.

**Comment by cwalo** [comment] 2017-09-29 15:24
@Jeyhey Going to close this since it sounds like you've got it figured out. 👍

**Closed as completed by cwalo** 2017-09-29 15:24 UTC
