### ISSUE TITLE
NSAttributedString link is not tapable

### ISSUE THREAD

**Issue by rulai-yinqiang** [MessageKit/MessageKit#636] opened 2018-04-08 02:01 UTC
I add a NSAttributedString with link like this:

```
let text = "click google link"
let range = text.range(of: "google")

let attributedText = NSMutableAttributedString(string: text)
attributedText.addAttribute(.link, value: "http://google.com", range: range)
```

It will show the link, but when I tap it, no event raised in didSelectURL.

**Comment by zhongwuzw** [comment] 2018-04-08 07:36
@rulai-yinqiang , we don't provide support for embedded link currently. We will enhance it  soon.

**Comment by SD10** [comment] 2018-05-04 23:37
Duplicate of #609

**Closed as completed by SD10** 2018-05-04 23:37 UTC
Labels: enhancement, feature request
