### ISSUE TITLE
Select Multiple messages and delete from conversation 

### ISSUE THREAD

**Issue by Rogger98** [MessageKit/MessageKit#1712] opened 2022-05-09 13:17 UTC
I want to display check box on left side ( for receiver ) and on right side ( for sender ) on long-press of message and want to delete selected messages.

Like this 
![main-qimg-cc4008c87556c1dd9204e193148ce49f-lq](https://user-images.githubusercontent.com/44162605/167418185-b56f6cc8-e498-4864-9d8d-035a1cca78de.jpeg)

**Comment by martinpucik** [comment] 2022-05-10 12:40
Hey @Rogger98 thanks for raising this. It seems like this is a duplicate of #447. Edit mode is not yet implemented in MessageKit but the code should be flexible enough for you to add the edit mode in your project directly

**Closed as completed by martinpucik** 2022-05-10 12:40 UTC
Labels: question
