### ISSUE TITLE
First chat message is overlapping (hiding behind) navigation bar

### ISSUE THREAD

**Issue by azhararmar** [MessageKit/MessageKit#300] opened 2017-10-30 16:22 UTC
## General Information

* MessageKit Version: 0.1.0

* iOS Version(s): 10.3.3

* Swift Version: 4

* Devices/Simulators: iPhone6s Device

* Reproducible in ChatExample? (Yes/No): No

##  What happened?
First chat message element is overlapping the navigation bar. find attached the screenshot.
![img_5846](https://user-images.githubusercontent.com/10097624/32182287-48780356-bdbc-11e7-8561-0c512607a561.PNG)

I've tested this in iOS11 using iPhone6 simulator and it works just fine.

This issue is seen only if fewer messages are available. Once the messages fills the screens this issue no more exist.

## What did you expect to happen?
Message element must not overlap the navigation bar.

**Comment by SD10** [comment] 2017-10-30 22:55
@azhararmar Have you modified any of these properties?

`extendedLayoutIncludedOpaqueBars`
`messagesCollectionView.contentInset.top`
`automaticallyAdjustsScrollInsets`

**Comment by nathantannar4** [comment] 2017-10-31 00:06
@azhararmar to add, are you using a standard `UINavigationController`?

**Comment by azhararmar** [comment] 2017-10-31 04:02
@SD10 I have modified only `messagesCollectionView.contentInset` after I noticed the issue, find below the code I use.

```
if SYSTEM_VERSION_LESS_THAN(version: "11.0") {
    self.messagesCollectionView.contentInset = UIEdgeInsetsMake(44, 0, 0, 0)
}
```
While I noticed this issue in iOS10, I am yet to test this on iOS9.

@nathantannar4 I am using custom navigation bar. here is the code I am using.

```
class CustomNavigationBar: UINavigationBar {
    override func awakeFromNib() {
        UINavigationBar.appearance().titleTextAttributes = [
            NSAttributedStringKey.foregroundColor: UIColor.black,
            NSAttributedStringKey.font: UIFont(name: "Montserrat-Light", size: 17)!
        ]
        UINavigationBar.appearance().tintColor = UIColor.black
        UINavigationBar.appearance().backgroundColor = UIColor.white
        // Hide Title Text
        UIBarButtonItem.appearance().setTitleTextAttributes([NSAttributedStringKey.foregroundColor: UIColor.clear], for: .normal)
        UIBarButtonItem.appearance().setTitleTextAttributes([NSAttributedStringKey.foregroundColor: UIColor.clear], for: .highlighted)
    }
}
```
I am also using several collectionview in my project, and none has this overlapping issue.

**Comment by azhararmar** [comment] 2017-10-31 06:28
Anyone else has tested this in iOS9/iOS10 and confirm this issue?

**Comment by nathantannar4** [comment] 2017-10-31 08:44
I can't reproduce it on the example yet

**Comment by brandon-haugen** [comment] 2017-10-31 16:09
I just noticed this today in an app I am working on that just recently started using MessageKit. It seems to only happen on iOS 10.x and it does happen in the simulator for iOS 10.3, you can see that the top of Steve Job's head is cut off under the nav bar.

<img width="475" alt="screen shot 2017-10-31 at 11 06 55 am" src="https://user-images.githubusercontent.com/182728/32234795-b13d611e-be2b-11e7-8ba6-499be4ddbcba.png">

This was building from 5365fcf79c97ab69 with Xcode 9.0.1

**Comment by nathantannar4** [comment] 2017-10-31 16:44
I found the issue. @SD10. In line 70 of `MessagesViewController` we set `automaticallyAdjustsScrollInsets` to false. In iOS 11 this doesn't seem to matter but in iOS < 11 it does. @SD10 do we need `automaticallyAdjustsScrollInsets` to be `false`? I tested it and this issue doesn't occur when `true`

**Comment by SD10** [comment] 2017-10-31 22:26
Hmmm @nathantannar4 Apple documentation says:

> Set this property to false if your view controller implementation manages its own scroll view inset adjustments.

I'll have to look into this further

**Comment by nathantannar4** [comment] 2017-10-31 22:34
@SD10, correct, but we never actually manage the top content inset. Alternatively we could do that but right now we are only managing the bottom. So perhaps we should address the top inset. But I tried that and you have to also manage it when the device is rotated

**Comment by nathantannar4** [comment] 2017-11-01 19:22
Steven and I have looked at this. The issue is related to the differences of `automaticallyAdjustsScrollInsets` in iOS 11 and iOS < 11

A solution we are evaluating is
```swift
if SYSTEM_VERSION_LESS_THAN(version: "11.0") {
    self. automaticallyAdjustsScrollInsets = true
}
```

**Comment by SD10** [comment] 2017-11-01 23:01
I feel like the inset is wrong because the code is wrong though. It doesn’t make sense for this flag to be true. I think it’s going to cause more problems by setting it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment] 2017-11-05 23:54
@SD10 Lets talk about this during our next ScreenHero session

**Comment by nathantannar4** [comment] 2017-11-07 07:56
PR #334

**Comment by SD10** [comment] 2017-11-12 20:58
@azhararmar This should be resolved in MessageKit 0.10.2, feel free to reopen if the problem continues

**Closed as completed by SD10** 2017-11-12 20:58 UTC
Labels: confirmed bug

**Comment by SD10** [comment] 2017-11-13 10:25
It looks like this issue might not be resolved. As @brandon-haugen mentioned it only happens on the physical device. I don't have any devices with iOS 10 :(

It looks like you will have to manage the top inset yourself for now

**Comment by azhararmar** [comment] 2017-11-13 10:59
I didn't test it yet with the update. Will test it once I get some time and report back.

For now I am indeed manually setting the inset the following way which is working quite good for me.

```
func SYSTEM_VERSION_LESS_THAN(version: String) -> Bool {
    return UIDevice.current.systemVersion.compare(
        version,
        options: NSString.CompareOptions.numeric
    ) == ComparisonResult.orderedAscending
}
```
```
if SYSTEM_VERSION_LESS_THAN(version: "11.0") {
    self.messagesCollectionView.contentInset = UIEdgeInsetsMake(59, 0, 0, 10)
} else {
    self.messagesCollectionView.contentInset = UIEdgeInsetsMake(10, 0, 0, 10)
}
```

**Comment by fsjohnson** [comment] 2019-03-24 21:35
Hi - for iOS 11/12, setting the content inset works well, but for iOS 10 unfortunately the first message is still hidden behind the navigationController. Any suggestions on what to do? 

I tried on iPhone 7 simulator / iOS 10.2.  
`messagesCollectionView.contentInset = UIEdgeInsets(top: 80, left: 0, bottom: 0, right: 0)`

Thanks!

**Comment by dizxlabs** [comment] 2019-04-09 20:21
I am struggling with the same issue. It is not working in IOS 10. Are there anybody found a solution for this issue?

**Comment by nathantannar4** [comment] 2019-04-09 21:07
A fix was implemented for 3.0.0

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fsjohnson** [comment] 2019-04-16 23:12
@nathantannar4 do you know when that will be released? Or do I need to use a specific branch? I just used `pod 'MessageKit'` - thanks!

**Comment by xsoti** [comment] 2020-02-17 14:53
If anyone else still have this issue, check if you are not using IQKeyboardManagerSwift. I did use it and adding `IQKeyboardManager.shared.disabledDistanceHandlingClasses.append(ChatViewController.self)`
did solve my problem

**Comment by alibstrd** [comment] 2021-01-10 17:56
> If anyone else still have this issue, check if you are not using IQKeyboardManagerSwift. I did use it and adding `IQKeyboardManager.shared.disabledDistanceHandlingClasses.append(ChatViewController.self)`
> did solve my problem

True hero

**Comment by mohammadtakbiri** [comment] 2024-07-18 07:02
Here is something that solved my problem:
self.messagesCollectionView.scrollToItem(at: IndexPath(row: self.messages.count - 1, section: 0), at: .top, animated: false)
