### ISSUE TITLE
messagesCollectionView is hidden by keyboard

### ISSUE THREAD

**Issue by Jeyhey** [MessageKit/MessageKit#165] opened 2017-09-25 22:42 UTC
When the soft keyboard is shown messagesCollectionView does not scroll up with the keyboard.

I guess the code that is supposed to handle is the line
 `messagesCollectionView.contentInset.bottom = bottomInset` 
in `handleKeyboardDidChangeState()`.

I don't know why, but I can only convince the collection view to move up when I insert a call to `messagesCollectionView.setContentOffset(someOffset)` right below this line.

**Comment by SD10** [comment] 2017-09-25 23:18
@Jeyhey You can still view all the content, correct? You're just talking about how the user has to manually scroll to the bottom of the `MessagesCollectionView`?

You can scroll to the bottom of `MessagesCollectionView` using the `scrollToBottom(animated:)` method. We probably want to add a flag to determine if this is done automatically when the keyboard is shown.

**Comment by alijaza** [comment] 2017-09-25 23:23
+1 The bottom contentinset is giving me all sorts of trouble. I can't get the messageInputBar to stop covering the CollectionView no matter what I do. Seems even if I set it view the view loads, handleKeyboardDidChangeState eventually changes it back to the wrong value. For some reason, when using the slack keyboard from the example project the messageInputBar height has the wrong value when this method fires.

**Comment by Jeyhey** [comment] 2017-09-25 23:25
@SD10 no the cells get hidden by the keyboard. I was talking about the behaviour of the collection view when the keyboard gets shown. I would expect some standard behaviour implemented in the base class of MessageViewController.

Following the lines of [https://developer.apple.com/library/content/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/KeyboardManagement/KeyboardManagement.html](url) I get the intuitive behaviour by changing the method to:
```
func handleKeyboardDidChangeState(_ notification: Notification) {

        guard let keyboardEndFrame = notification.userInfo?[UIKeyboardFrameEndUserInfoKey] as? CGRect else { return }

        if (keyboardEndFrame.origin.y + keyboardEndFrame.size.height) > view.frame.size.height {
            // Hardware keyboard is found
            messagesCollectionView.contentInset.bottom = view.frame.size.height - keyboardEndFrame.origin.y
        } else {
            //Software keyboard is found
            let bottomInset = keyboardEndFrame.height > messageInputBar.frame.height ? keyboardEndFrame.height : messageInputBar.frame.height
            messagesCollectionView.contentInset.bottom = bottomInset
        }
        var aRect = self.view.frame
        aRect.size.height -= keyboardEndFrame.height
        if let indexPath = messagesCollectionView.indexPathForLastItem, let activeField = messagesCollectionView.cellForItem(at: indexPath) {
            if (!aRect.contains(activeField.frame.origin) ) {
                messagesCollectionView.scrollRectToVisible(activeField.frame, animated: true)
            }
        }
    }
```
edit: had to make `messagesCollectionView.indexPathForLastItem()` public for that.

**Comment by Jeyhey** [comment] 2017-09-25 23:27
This will scroll the collection view upon keyboard is shown if the last cell is at least partially visible at the moment the keyboard starts moving up. If it is not visible at all at that point in time, the collection view does not scroll.

**Comment by SD10** [comment] 2017-09-25 23:36
@alijaza Thanks for the feedback I'm aware of that problem and will look into resolving it tonight. 👍 

@Jeyhey Can you give me any screenshots of the issue? I'm having trouble following. I'm also available on [Slack](https://messagekit.slack.com/join/shared_invite/MjI4NzIzNzMyMzU0LTE1MDMwODIzMDUtYzllYzIyNTU4MA) if you want to speak directly.

**Comment by Jeyhey** [comment] 2017-09-25 23:49
The issue I'm referring to is the one shown in the first few seconds of this video: https://www.youtube.com/watch?v=AiYCStoj0lc

**Comment by etoledom** [comment] 2017-09-25 23:55
About this automatic content scrol when keyboard appears, there are (at least) 3 different possible behaviors:

- Messages (scroll view content) scrolls with the keyboard, wherever the scroll offset is. (Ej: WhatsApp, Telegram)

- Messages scroll always to bottom, showing the last message, wherever the scroll offset is (I.e: Apple messages)

- Messages scrolls with the keyboard just if it is showing the last message, so the last message is still visible, but text doesn’t scroll in any other case (I.e: Slack iOS)

I think we should at least make easy for any of this cases to be imol mentes and maybe implement one of them by default.

**Comment by SD10** [comment] 2017-09-26 00:00
@Jeyhey What I want to know is if you scroll down after the keyboard is shown can you see the content? I'm trying to figure out if this is a bug or a feature request.

@etoledom I agree. Trying to clarify what we both think the issue is

**Comment by Jeyhey** [comment] 2017-09-26 05:51
Ok, I see. My issue is not with the behaviour of the collection view when making it scroll. It is with the behaviour of the collection view (i. e. its lack of reaction) when making the keyboard appear (by tapping in the input bar text view).

**Closed as completed** 2017-10-04 04:28 UTC
Labels: feature request
