### ISSUE TITLE
TailCorner bottomLeft not working in iOS 9

### ISSUE THREAD

**Issue by tflin** [MessageKit/MessageKit#468] opened 2018-01-18 05:46 UTC
## General Information

* MessageKit Version: 0.13.0

* iOS Version(s): iOS 9.3.5

* Swift Version: 4.0

* Devices/Simulators: iPhone/iPod

* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?

In iOS 9 the ChatExample:
![img_0809](https://user-images.githubusercontent.com/12755752/35082613-d6970ed4-fc55-11e7-8f33-076625168ee2.PNG)

## What did you expect to happen?
As in iOS 11, ChatExample:

![img_1927](https://user-images.githubusercontent.com/12755752/35082641-f1037726-fc55-11e7-886b-d95c501c17e0.PNG)

**Comment by tflin** [comment] 2018-01-18 06:00
Maybe the same with issue #376. 
The problem may be on the lines in MessageStyle.swift:

case .bubbleTail(let corner, _), .bubbleTailOutline(_, let corner, _):
            guard let cgImage = image.cgImage else { return nil }
            image = UIImage(cgImage: cgImage, scale: image.scale, orientation: corner.imageOrientation)

The generated UIImage is not flip horizontally as expected in iOS 9.

**Comment by SD10** [comment] 2018-01-18 12:27
@tflin thanks for reporting this. Yes, it’s a duplicate of #376

iOS 9 is pretty low priority. If you have a way to fix this one feel free to submit a PR. It looks like the insets for the text label is also wrong on iOS 9

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment] 2018-01-18 12:35
Closing in favor of #376 👍

**Closed as completed by BasThomas** 2018-01-18 12:35 UTC
Labels: confirmed bug, priority: low

**Comment by zhongwuzw** [comment] 2018-01-19 01:37
@tflin , Thanks for your issue, we have fixed it and will release in next version.

**Comment by tflin** [comment] 2018-01-19 01:42
@zhongwuzw Nice job! 好樣的!

**Comment by zhongwuzw** [comment] 2018-01-19 01:45
@tflin ,谢谢！
