### ISSUE TITLE
group image white get/send many photo like facebook/skype 

### ISSUE THREAD

**Issue by fukemy** [MessageKit/MessageKit#1375] opened 2020-06-05 09:40 UTC
hello, thanks for your library, i want to ask the case multi image display in one message, did your library support this feature? Thanks
![Screen Shot 2020-06-05 at 16 40 04](https://user-images.githubusercontent.com/8202437/83861787-3ca42e80-a74b-11ea-999c-e06610907de6.png)

**Comment by kinoroy** [comment] 2020-06-05 19:05
This isn't yet an included cell type however you can use a custom cell for this. Closing this issue as its a duplicate of #398

**Closed as completed by kinoroy** 2020-06-05 19:05 UTC
Labels: duplicate, feature request
