### ISSUE TITLE
[InputBar Bug] Rejected resignFirstResponder when being removed from hierarchy

### ISSUE THREAD

**Issue by Ludotrico** [MessageKit/MessageKit#1518] opened 2021-01-04 20:16 UTC
**Issue:**
The input bar is not dismissed. 

**To reproduce:**
1.) Make MessageVC a child of another VC.
2.) begin typing in input bar
3.) Call resignFirstResponder()
4.) Notice that "rejected resignFirstResponder when being removed from hierarchy" is printed to the console and the input bar can never be dismissed

Similar to this [issue](https://github.com/nathantannar4/InputBarAccessoryView/issues/178).

**Comment by Kaspik** [comment] 2021-03-04 22:13
Closing as it's an issue with input bar accessory view and the issue is there.

Based on the issue it seems like an iOS bug.

**Closed as completed by Kaspik** 2021-03-04 22:13 UTC
Labels: bug?
