### ISSUE TITLE
MESSagesViewController no senderID

### ISSUE THREAD

**Issue by reginaagst** [MessageKit/MessageKit#835] opened 2018-08-31 22:57 UTC

**Comment by reginaagst** [comment] 2018-08-31 23:04
JSQMESSagesViewController has a senderId.  I substituted the MESSagesViewController in place of the JSQMESSagesViewController in my project .  when I use the messagesViewController and I use the senderID I am getting an error my question is there a replacement for senderId in MESSagesViewController . Also I am not able to open the chatExample project https://github.com/MessageKit/MessageKit/tree/master/Example
<img width="1166" alt="screen shot 2018-08-31 at 6 58 17 pm" src="https://user-images.githubusercontent.com/38174510/44939053-6ba89780-ad50-11e8-9cfc-c178c344be10.png">
<img width="932" alt="screen shot 2018-08-31 at 6 58 38 pm" src="https://user-images.githubusercontent.com/38174510/44939054-6ba89780-ad50-11e8-8129-57a1be079b0e.png">

**Comment by nathantannar4** [comment] 2018-08-31 23:04
@reginaagst can you please explain your issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment] 2018-08-31 23:05
@reginaagst MessageKit is not an identical replacement of JSQ. It is quite different. Please take a look at our guides and example project. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by reginaagst** [comment] 2018-08-31 23:06
the example project I cannot open it

**Comment by reginaagst** [comment] 2018-08-31 23:07
when I click on the project it does not give me the option to clone it

**Comment by reginaagst** [comment] 2018-08-31 23:07
https://github.com/MessageKit/MessageKit/tree/master/Example

**Comment by nathantannar4** [comment] 2018-09-01 01:34
@reginaagst Please keep the discussion relevant to the issue you raised. You already opened an issue for your troubles with finding the example. Closing as this seems to be a duplicate of #836

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed as completed by nathantannar4** 2018-09-01 01:34 UTC
