### ISSUE TITLE
Add support for status message like time in iMessage

### ISSUE THREAD

**Issue by neal** [MessageKit/MessageKit#561] opened 2018-03-15 07:44 UTC
Would be useful to have an ability to add some kind of status message like the time shown in iMessage: small centered text.

**Comment by SD10** [comment] 2018-03-15 19:16
@Neal This is a good suggestion but I’m trying to reduce complexity right now. I don’t know how to solve some of the existing problems we have. Until then, I don’t want to add new functionality 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by neal** [comment] 2018-03-17 09:55
@SD10 Fair enough.

Although I got it to work without modifying anything if anyone needs this by using `MessageStyle.none`, `MessageData.attributedText` and a `system` sender ID for the messages to check in each delegate method and returning `footerViewSize`, `messagePadding`, etc. accordingly. 

A little hacky but does the job.

**Comment by SD10** [comment] 2018-03-23 05:57
Hey @Neal,

I'm glad you were able to get this resolved 😃 Do you think this is a duplicate of #190?

**Comment by neal** [comment] 2018-03-23 08:24
@SD10 I actually meant being able to add messages like "Today 4:05 PM" in that screenshot. #190 is for accessory view so not a dupe. Although I have now realized there is a `headerView` already that does draw time like that but even then a separate `MessageType` to add custom messages like "Missed call on ..." or "User key has changed" or "John has been added to the conversation" would be nice.

**Comment by kinoroy** [comment] 2020-02-19 06:55
With `MessageKind.custom`, you can create custom messages like "John has been added to the conversation". Closing since outdated.

**Closed as completed by kinoroy** 2020-02-19 06:55 UTC
Labels: feature request
