### ISSUE TITLE
Is there any working example using the current version Messagekit(1.0.0)? I have been using the example provided but it doesnot work as expected.  

### ISSUE THREAD

**Issue by nirajhi** [MessageKit/MessageKit#814] opened 2018-08-14 11:01 UTC
<!--
Hi, thanks so much for opening an issue! 🤗

To better pinpoint (and solve) the issue you're experiencing, we could use some information on your behalf.

Please let us know the following things:

- What version of MessageKit are you using?
1.0.0

- What version of iOS are you running on?
-11.4.1

- What version of Swift are you running on?
swift4

- What device(s) are you testing on? Are these simulators?
IphoneX

- Is the issue you're experiencing reproducable in the example app?
Yes

**Comment by SD10** [comment] 2018-08-14 13:53
Hey @nirajhi, this is a duplicate of #760. You can check out #803 which is a PR upgrading the example app. Going to close this one as it's already being tracked 👍

**Closed as completed by SD10** 2018-08-14 13:53 UTC
Labels: question
