### ISSUE TITLE
EXC_BAD_ACCESS (code=2, address=0x16d07bff0) at override var inputAccessoryView:

### ISSUE THREAD

**Issue by MiteshiOS** [MessageKit/MessageKit#1849] opened 2024-07-01 05:34 UTC
Embedded Example, crash on tap of typing area. 

The example is giving errors like EXC_BAD_ACCESS (code=2, address=0x16d07bff0 in the below methods.

```
/// Required for the `MessageInputBar` to be visible
  override var inputAccessoryView: UIView? {
    conversationViewController.inputAccessoryView
  }
```

This method is available in MessageContainerController.

- I am running an example in the simulator. 
- XCode Version 15.4
- MacOS Version 14.5

![Screenshot 2024-07-01 at 10 59 27 AM](https://github.com/MessageKit/MessageKit/assets/17427703/169d9281-98ca-4300-9ae9-ab033dc8bb39)

**Comment by Kaspik** [comment] 2024-07-11 08:54
This is not bug on our side, but in your implementation - based on the stack you are in loop cycle.

**Comment by Kaspik** [comment] 2024-07-11 08:58
Also duplicate of https://github.com/MessageKit/MessageKit/issues/1846

**Closed as completed by Kaspik** 2024-07-11 08:58 UTC
Labels: duplicate

**Comment by MiteshiOS** [comment] 2024-07-11 10:15
This is the official Chat Example provided in the repo itself.
To reproduce please follow these steps.
1) Go to MessageKit-main -> Example -> ChatExample.xcworkspace
2) Run the project
3) Select Embedded Example
4) On navigating to the Embedded example screen try to type something in the typing area.
Example app will crash due to above mentioned reason
